const assert = require('node:assert/strict');
require('../web/selection-store.js');

const item = (id, pages, restriction = 'safe') => ({id, pages, restriction});
const origin = {context: {kind: 'tags', value: 'cat'}, resultPage: 1};
const selection = createSelectionStore({maxPages: 5});
assert.equal(selection.choose([item('a', 3)], origin).accepted, true);
assert.equal(selection.choose([item('b', 3)], origin).accepted, false);
assert.equal(selection.pageCount, 3);
assert.equal(selection.has('b'), false);
assert.equal(selection.size, 1);
assert.equal(selection.choose([item('c', 1), item('invalid', -1)], origin).accepted, false);
assert.equal(selection.has('c'), false, 'invalid bulk choice partially changed the basket');
assert.equal(selection.choose([item('huge', Number.MAX_SAFE_INTEGER)], origin).accepted, false);
assert.equal(selection.setPage(item('a', 3), 0, false, origin).accepted, true);
assert.equal(selection.pageCount, 2);
assert.equal(selection.choose([item('a', 3), item('b', 3)], origin, {fill: true}).accepted, false);
assert.deepEqual([...selection.get('a').pages], [1, 2]);
const copy = selection.get('a');
copy.pages.clear();
copy.context.value = 'changed';
assert.equal(selection.pageCount, 2);
assert.equal(selection.get('a').context.value, 'cat');
assert.equal(selection.choose([item('a', 3)], {context: {kind: 'uid', value: '9'}, resultPage: 8}).accepted, true);
assert.equal(selection.get('a').context.value, 'cat');
assert.equal(selection.get('a').resultPage, 1);
selection.setPage(item('b', 3), 0, true, origin);
selection.setPage(item('b', 3), 0, false, origin);
assert.equal(selection.has('b'), false, 'last unchecked page left an empty artwork record');
selection.archive(['a']);
assert.equal(selection.archivedCount, 1);
selection.setLocked(true);
assert.equal(selection.clear().accepted, false);
assert.equal(selection.setPage(item('a', 3), 1, false, origin).accepted, false);
selection.revoke(['a']);
assert.equal(selection.size, 0);
assert.equal(selection.pageCount, 0);
assert.equal(selection.archivedCount, 0);
